# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

language: scala
scala:
  - 2.11.11
  - 2.10.6
jdk:
  - openjdk7

script:
  - git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
  - git show --oneline --check
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m check-gen-type-classes "project $TEST_PROJECT" test:compile mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION "project $TEST_PROJECT" test "project /" $(if [[ "${TEST_PROJECT}" == "rootJVM" ]]; then echo "publishLocal"; fi)

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

matrix:
  include:
    - scala: 2.13.0-M1
      jdk: oraclejdk8
      env: TEST_PROJECT="rootJVM"
      script:
      - sbt ++${TRAVIS_SCALA_VERSION} -J-Xmx3784m check-gen-type-classes "project $TEST_PROJECT" test
    - scala: 2.13.0-M1
      jdk: oraclejdk8
      env: TEST_PROJECT="rootJS"
      script:
      - sbt ++${TRAVIS_SCALA_VERSION} -J-Xmx3784m check-gen-type-classes "project $TEST_PROJECT" test
    - scala: 2.12.2
      jdk: oraclejdk8
      env: TEST_PROJECT="rootJVM"
    - scala: 2.12.2
      jdk: oraclejdk8
      env: TEST_PROJECT="rootJS"
    - scala: 2.11.11
      jdk: oraclejdk8
      sudo: required
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.2/bin/travis_setup.sh | bash -
      script:
      - ./sbt ++$TRAVIS_SCALA_VERSION nativeTest/run nativeTest/publishLocal

env:
  matrix:
  - TEST_PROJECT="rootJVM"
  - TEST_PROJECT="rootJS"

addons:
  apt:
    packages:
      - oracle-java8-installer
