language: scala
scala:
  - 2.10.1
  - 2.9.2
  - 2.9.3
jdk:
  - oraclejdk7
  - openjdk6

script: sbt ++$TRAVIS_SCALA_VERSION ';mima-report-binary-issues;set scalazMimaBasis in ThisBuild := "7.0.1";mima-report-binary-issues;set scalazMimaBasis in ThisBuild := "7.0.2";mima-report-binary-issues;set scalazMimaBasis in ThisBuild := "7.0.3";mima-report-binary-issues'
