# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
language: scala
scala:
  - 2.11.11
  - 2.10.6
  - 2.9.3
jdk:
  - openjdk7

script:
  - git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
  - git show --oneline --check
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m checkGenTypeClasses test mimaReportBinaryIssues publishLocal

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

matrix:
  include:
    - scala: 2.12.4
      jdk: oraclejdk8
    - scala: 2.13.0-M3
      jdk: oraclejdk8
      script:
      - git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
      - git show --oneline --check
      - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m checkGenTypeClasses test publishLocal

addons:
  # https://github.com/travis-ci/travis-ci/issues/5227
  hosts: workaround-travis-ci-issue-5227
  hostname: workaround-travis-ci-issue-5227
