# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
dist: precise # trusty does not support java6 and java7 ?
language: scala
scala:
  - 2.11.11
  - 2.10.6
  - 2.9.3
jdk:
  - oraclejdk7
  - openjdk6

script:
  - git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
  - git show --oneline --check
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m check-gen-type-classes test mimaReportBinaryIssues

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

matrix:
  include:
    - scala: 2.12.2
      jdk: oraclejdk8
    - scala: 2.13.0-M2
      jdk: oraclejdk8
      script:
      - git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
      - git show --oneline --check
      - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m check-gen-type-classes test
      - find $HOME/.sbt -name "*.lock" | xargs rm
      - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

addons:
  apt:
    packages:
      - oracle-java8-installer
