# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

language: scala
scala:
  - 2.12.0-M1
jdk:
  - oraclejdk7
  - openjdk6

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m test mima-report-binary-issues
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
