name: scala-steward
on:
  push:
  schedule:
  - cron: '0 0 * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
    - uses: laughedelic/coursier-setup@v1
    - run: cs install scalafmt
    - name: Launch Scala Steward
      if: ${{ !github.event.repository.fork }}
      uses: scala-steward-org/scala-steward-action@8e358d73d042a351ee010a74882ad0edf7070512
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
